### ISSUE TITLE
Graph displays  different with neo4j browser

### ISSUE THREAD

**Issue by sduchh** [jexp/cy2neo#1]
Hi, the workbench is very useful for me. Thanks very much for the contribution. But graph displayed in this workbench is still different from that in neo4j browser. For example, though I have changed the color and the border-width of the node in the neo4j browser, nodes queried from the workbench are still the same with before .In addition, the properties of the node can not display when clicking it just as in neo4j browser.  Besides, labels of nodes are not displayed. Can you give me some help? Thanks very much.

![cy2neo](https://cloud.githubusercontent.com/assets/8318122/5108512/de6f792e-7045-11e4-9a9b-14652597f817.jpg)
![neo4j](https://cloud.githubusercontent.com/assets/8318122/5108536/ffb82b08-7045-11e4-8a3f-2ce07411fb74.jpg)

**Comment by jexp** [comment]
This is just a demo using a javascript library that partially does what the browser does.

It is here for people that want to take it and continue to experiment with it. So feel free to do so.
I'm not sure I have time to add all browser functions to this demo.
